//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deposits")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub deposit_id: Uuid,
    pub currency: String,
    pub network: String,
    pub wallet_address: String,
    pub amount_received: String,
    pub payment_status: String,
    pub confirmations: Option<i32>,
    pub txid: Option<String>,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub finalized: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
