//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

// use sea_orm::entity::prelude::*;

// #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
// #[sea_orm(table_name = "invoices")]
// pub struct Model {
//     #[sea_orm(primary_key, auto_increment = false)]
//     pub invoice_id: Uuid,
//     pub currency: String,
//     pub network: String,
//     pub wallet_address: String,
//     pub amount_requested: String,
//     pub amount_received: String,
//     pub payment_status: String,
//     pub confirmations: Option<i32>,
//     #[sea_orm(column_type = "JsonBinary", nullable)]
//     pub transactions: Option<Json>,
// }

// #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
// pub enum Relation {}

// impl ActiveModelBehavior for ActiveModel {}
