//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "litecoin_wallet")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub account_index: i32,
    pub address_index: i32,
    #[sea_orm(unique)]
    pub wallet_address: String,
    pub created_at: DateTime,
    pub last_used_at: Option<DateTime>,
    pub blockchain_height: i32,
    pub is_available: Option<bool>,
    pub is_change: bool,
    pub initial_balance: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
