//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "monero_wallet")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub major_index: i32,
    pub minor_index: i32,
    pub wallet_address: String,
    pub created_at: DateTime,
    pub last_used_at: Option<DateTime>,
    pub blockchain_height: i32,
    pub is_available: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
