//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

// pub use super::deposits::Entity as Deposits;
// pub use super::fiat_prices::Entity as FiatPrices;
// pub use super::invoices::Entity as Invoices;
// pub use super::litecoin_wallet::Entity as LitecoinWallet;
// pub use super::monero_wallet::Entity as MoneroWallet;
// pub use super::tokens::Entity as Tokens;
